// <auto-generated />
using System;
using Cine.Modules.Shows.Infrastructure.Database.Write;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cine.Modules.Shows.Infrastructure.Database.Migrations
{
    [DbContext(typeof(WriteContext))]
    partial class WriteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cine.Modules.Shows.Domain.Hall", b =>
                {
                    b.Property<Guid>("HallId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HallId");

                    b.ToTable("Halls", (string)null);
                });

            modelBuilder.Entity("Cine.Modules.Shows.Domain.Movies", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("Duration")
                        .HasColumnType("time");

                    b.HasKey("MovieId");

                    b.ToTable("Movies", (string)null);
                });

            modelBuilder.Entity("Cine.Modules.Shows.Domain.Show", b =>
                {
                    b.Property<Guid>("ShowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShowId");

                    b.ToTable("Shows", (string)null);
                });

            modelBuilder.Entity("Cine.Shared.Application.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Cine.Modules.Shows.Domain.Show", b =>
                {
                    b.OwnsOne("Cine.Modules.Shows.Domain.Schedule", "ScheduledAt", b1 =>
                        {
                            b1.Property<Guid>("ShowId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<TimeSpan>("Duration")
                                .HasColumnType("time")
                                .HasColumnName("Duration");

                            b1.Property<DateTime>("StartAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("StartAt");

                            b1.HasKey("ShowId");

                            b1.ToTable("Shows");

                            b1.WithOwner()
                                .HasForeignKey("ShowId");
                        });

                    b.Navigation("ScheduledAt")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
