<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Rules\" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Cine.Modules.Sales.Domain.UnitTests" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\Cine.Shared.Domain\Cine.Shared.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Ardalis.SmartEnum" />
    </ItemGroup>

</Project>
