<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Hangfire" />
      <PackageReference Include="Hangfire.InMemory" />
      <PackageReference Include="MediatR" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\Cine.Shared.Infrastructure\Cine.Shared.Infrastructure.csproj" />
      <ProjectReference Include="..\Cine.Modules.Tickets.Application\Cine.Modules.Tickets.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Database\Migrations\" />
    </ItemGroup>

</Project>
