services:
  cine.modules.movies.api:
    container_name: movies
    image: ${DOCKER_REGISTRY-}cine.module.movies.api
    build:
      context: .
      dockerfile: src/Modules/Movies/Cine.Modules.Movies.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
    depends_on:
      - mssql
      - rabbitmq
  
  cine.modules.tickets.api:
    container_name: tickets
    image: ${DOCKER_REGISTRY-}cine.module.tickets.api
    build:
      context: .
      dockerfile: src/Modules/Tickets/Cine.Modules.Tickets.Api/Dockerfile
    ports:
      - "8081:8081"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
    depends_on:
      - mssql
      - rabbitmq
  
  cine.modules.theater.api:
    container_name: theater
    image: ${DOCKER_REGISTRY-}cine.module.theater.api
    build:
      context: .
      dockerfile: src/Modules/Theater/Cine.Modules.Theater.Api/Dockerfile
    ports:
      - "8082:8082"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
    depends_on:
      - mssql
      - rabbitmq
  
  cine.modules.shows.api:
    container_name: shows
    image: ${DOCKER_REGISTRY-}cine.module.shows.api
    build:
      context: .
      dockerfile: src/Modules/Shows/Cine.Modules.Shows.Api/Dockerfile
    ports:
      - "8083:8083"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
    depends_on:
      - mssql
      - rabbitmq
  
  cine.modules.sales.api:
    container_name: sales
    image: ${DOCKER_REGISTRY-}cine.modules.sales.api
    build:
      context: .
      dockerfile: src/Modules/Sales/Cine.Modules.Sales.Api/Dockerfile
    ports:
      - "8084:8084"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
    depends_on:
      - mssql
      - rabbitmq

  mssql:
    container_name: ms-sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "W88QnBWn"
      MSSQL_PID: 'Developer'
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"