@host = http://localhost:8080

POST {{host}}/person/add
Accept: application/json
Content-Type: application/json

{
  "firstName": "Clint",
  "lastName": "Eastwood"
}

###

GET {{host}}/person/get
Accept: application/json
Content-Type: application/json

{
  "personId": "4993dbca-eb9e-4e88-84af-bb58db2afa3c"
}

###

POST {{host}}/movie/add
Accept: application/json
Content-Type: application/json

{
  "title": "The Matrix",
  "description": "Matrix is a science fiction action film written and directed by the Wachowski brothers.",
  "genre": "SciFi",
  "duration": "02:16:00",
  "releaseDate": "1999-03-31",
  "directors": [
    { "FirstName": "Larry", "LastName": "Wachowski" },
    { "FirstName": "Andy", "LastName": "Wachowski" }
  ],
  "cast": [
    { "FirstName": "Keanu", "LastName": "Reeves" }
  ]
}

###

GET {{host}}/movie/get
Accept: application/json
Content-Type: application/json

{
  "movieId": ""
}

###