@host = http://localhost:8081
@showId = 75eed93c-7d17-4c24-9ddd-d48c0a6b720e
@reservationId = c8de1c56-d0b2-43c8-a496-3bdbe3a611b6
@seatId = 39554e65-d415-44b1-9f01-97b90e033d14

POST {{host}}/reservation/create
Accept: application/json
Content-Type: application/json

{
  "ShowId": "{{showId}}"
}

###

POST {{host}}/reservation/{{reservationId}}/addSeat/{{seatId}}
Accept: application/json
Content-Type: application/json

{
}

###

POST {{host}}/reservation/{{reservationId}}/removeSeat/{{seatId}}
Accept: application/json
Content-Type: application/json

{
}

###

POST {{host}}/reservation/{{reservationId}}/confirm
Accept: application/json
Content-Type: application/json

{
}

###

GET {{host}}/reservations/{{reservationId}}
Accept: application/json

{
}