<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FastEndpoints" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Cine.Modules.Tickets.Application\Cine.Modules.Tickets.Application.csproj" />
      <ProjectReference Include="..\Cine.Modules.Tickets.Infrastructure\Cine.Modules.Tickets.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Endpoints\Reservations\RemoveSeat\" />
    </ItemGroup>

    <ItemGroup>
      <PackageVersion Update="FastEndpoints" Version="5.32.0" />
    </ItemGroup>

</Project>
