@host = http://localhost:8081
@showId = 2e437e47-967b-46d4-8e75-77d72df5cb07
@reservationId = bdceb620-0769-4a72-bfb2-558633583442
@seatId = ade8c473-4870-48d5-82b2-0833bf86e0db

POST {{host}}/reservation/create
Accept: application/json
Content-Type: application/json

{
  "ShowId": "{{showId}}"
}

###

POST {{host}}/reservation/{{reservationId}}/addSeat/{{seatId}}
Accept: application/json
Content-Type: application/json

{
}

###

POST {{host}}/reservation/{{reservationId}}/removeSeat/{{seatId}}
Accept: application/json
Content-Type: application/json

{
}

###

POST {{host}}/reservation/{{reservationId}}/confirm
Accept: application/json
Content-Type: application/json

{
}