// <auto-generated />
using System;
using System.Collections.Generic;
using Cine.Modules.Tickets.Infrastructure.Database.Write;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cine.Modules.Tickets.Infrastructure.Database.Migrations
{
    [DbContext(typeof(WriteContext))]
    [Migration("20250106164656_Seat_ReservationId_NotRequired")]
    partial class Seat_ReservationId_NotRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cine.Modules.Tickets.Domain.Reservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShowId")
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("ReservationStatusRepresentation", "Cine.Modules.Tickets.Domain.Reservation.ReservationStatusRepresentation#ReservationStatusRepresentation", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Discriminator")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("StatusType");

                            b1.Property<DateTime?>("ExpiredAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("ExpiredAt");

                            b1.Property<DateTime?>("PaidAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("PaidAt");

                            b1.Property<DateTime?>("ReservedAt")
                                .HasColumnType("datetime2")
                                .HasColumnName("ReservedAt");
                        });

                    b.HasKey("ReservationId");

                    b.ToTable("Reservations", (string)null);
                });

            modelBuilder.Entity("Cine.Modules.Tickets.Domain.Seat", b =>
                {
                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeatId");

                    b.HasIndex("ReservationId");

                    b.ToTable("Seats", (string)null);
                });

            modelBuilder.Entity("Cine.Modules.Tickets.Domain.Show", b =>
                {
                    b.Property<Guid>("ShowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HallId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShowId");

                    b.ToTable("Shows", (string)null);
                });

            modelBuilder.Entity("Cine.Shared.Application.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Cine.Modules.Tickets.Domain.Seat", b =>
                {
                    b.HasOne("Cine.Modules.Tickets.Domain.Reservation", "Reservation")
                        .WithMany("Seats")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Cine.Modules.Tickets.Domain.Reservation", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
