<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    <InternalsVisibleTo Include="Cine.Modules.Movies.Application.UnitTests" />
    <InternalsVisibleTo Include="Cine.Modules.Movies.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Cine.Shared.Application\Cine.Shared.Application.csproj" />
    <ProjectReference Include="..\..\..\Shared\Cine.Shared.Infrastructure\Cine.Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\Cine.Modules.Movies.Domain\Cine.Modules.Movies.Domain.csproj" />
    <ProjectReference Include="..\Cine.Modules.Movies.IntegrationEvents\Cine.Modules.Movies.IntegrationEvents.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="OneOf" />
    <PackageReference Include="Scrutor" />
  </ItemGroup>

</Project>
