<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Cine.Modules.Sales.Application" />
        <InternalsVisibleTo Include="Cine.Modules.Sales.Infrastructure" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MassTransit" />
      <PackageReference Include="MassTransit.Abstractions" />
      <PackageReference Include="OneOf" />
      <PackageReference Include="Refit" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Cine.Modules.Sales.Domain\Cine.Modules.Sales.Domain.csproj" />
    </ItemGroup>

</Project>
