@host = http://localhost:8082
@hallId = dc6428b5-498b-4515-9e21-44791965f729

POST {{host}}/hall/add
Accept: application/json
Content-Type: application/json

{
  "name": "Hall #2",
  "seatRows": 2,
  "seatsPerRow": 4,
  "premiumSeats": []
}

###

GET {{host}}/halls/{{hallId}}/seats
Accept: application/json
Content-Type: application/json

{
}